In [191]:
import numpy as np
import pandas as pd

In [192]:
from google.colab import files

uploaded = files.upload()

Saving Ecommerce_Unclean_Project.xlsx to Ecommerce_Unclean_Project (4).xlsx

In [193]:
df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [194]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [196]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [197]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [198]:
df.duplicated().sum()

np.int64(11)

In [199]:
df.drop_duplicates(inplace=True)

In [200]:
df.replace(['N/A', 'NULL', 'null', 'n/a'], np.nan, inplace=True)

In [201]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [202]:
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [203]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [204]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'email', 'phone', 'city',
       'state', 'product', 'category', 'qty', 'unit_price', 'discount',
       'payment_mode', 'order_status', 'delivery_date'],
      dtype='object')

In [205]:
df.head(10)

,order_id,order_date,customer_name,email,phone,city,state,product,category,qty,unit_price,discount,payment_mode,order_status,delivery_date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20,Wallet,Cancelled,18-02-2025
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
7,ORD1009,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
8,ORD1010,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
9,ORD1011,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025

In [206]:
df = df[df['qty'] > 0]

In [207]:
df['discount'] = df['discount'].fillna(0)
df['phone'] = df['phone'].fillna('Unknown')
df['delivery_date'] = df['delivery_date'].fillna(df['order_date'])

In [208]:
df['total_sales'] = df['qty'] * df['unit_price']

In [209]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'email', 'phone', 'city',
       'state', 'product', 'category', 'qty', 'unit_price', 'discount',
       'payment_mode', 'order_status', 'delivery_date', 'total_sales'],
      dtype='object')

In [210]:
df['discount'] = pd.to_numeric(df['discount'], errors='coerce')

In [211]:
df['discount'] = df['discount'].fillna(0)

In [212]:
df['net_amount'] = df['total_sales'] * (1 - df['discount'] / 100)

In [213]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'email', 'phone', 'city',
       'state', 'product', 'category', 'qty', 'unit_price', 'discount',
       'payment_mode', 'order_status', 'delivery_date', 'total_sales',
       'net_amount'],
      dtype='object')

In [214]:
df['profit'] = df['net_amount'] * 0.20

In [215]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

/tmp/ipykernel_3508/2225214990.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [216]:
df['order_month'] = df['order_date'].dt.month_name()

In [217]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'email', 'phone', 'city',
       'state', 'product', 'category', 'qty', 'unit_price', 'discount',
       'payment_mode', 'order_status', 'delivery_date', 'total_sales',
       'net_amount', 'profit', 'order_month'],
      dtype='object')

In [218]:
df['order_year'] = df['order_date'].dt.year
df['order_weekday'] = df['order_date'].dt.day_name()

In [219]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'email', 'phone', 'city',
       'state', 'product', 'category', 'qty', 'unit_price', 'discount',
       'payment_mode', 'order_status', 'delivery_date', 'total_sales',
       'net_amount', 'profit', 'order_month', 'order_year', 'order_weekday'],
      dtype='object')

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       393 non-null    object
 1   order_date     345 non-null    datetime64[ns]
 2   customer_name  393 non-null    object
 3   email          393 non-null    object
 4   phone          393 non-null    object
 5   city           393 non-null    object
 6   state          393 non-null    object
 7   product        393 non-null    object
 8   category       393 non-null    object
 9   qty            393 non-null    float64
 10  unit_price     355 non-null    float64
 11  discount       393 non-null    float64
 12  payment_mode   393 non-null    object
 13  order_status   393 non-null    object
 14  delivery_date  393 non-null    object
 15  total_sales    355 non-null    float64
 16  net_amount     355 non-null    float64
 17  profit         355 non-null    float64
 18  order_month    345 non-null    object
 19  order_year     345 non-null    float64
 20  order_weekday  345 non-null    object
dtypes: datetime64[ns](1), float64(7), object(13)
memory usage: 67.5+ KB

In [221]:
df.isnull().sum()

order_id          0
order_date       48
customer_name     0
email             0
phone             0
city              0
state             0
product           0
category          0
qty               0
unit_price       38
discount          0
payment_mode      0
order_status      0
delivery_date     0
total_sales      38
net_amount       38
profit           38
order_month      48
order_year       48
order_weekday    48
dtype: int64

In [222]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [223]:
df = df.dropna(subset=['order_date'])

In [224]:
df[df['order_date'].isna()]

Empty DataFrame
Columns: [order_id, order_date, customer_name, email, phone, city, state, product, category, qty, unit_price, discount, payment_mode, order_status, delivery_date, total_sales, net_amount, profit, order_month, order_year, order_weekday]
Index: []

[0 rows x 21 columns]

In [225]:
missing_products = df.loc[df['unit_price'].isna(), 'product'].unique()

df[df['product'].isin(missing_products)][
    ['product', 'category', 'unit_price']
].sort_values('product')

    product category  unit_price
225  Bottle     Home       499.0
162  Bottle     Home      2599.0
316  Bottle     Home       499.0
314  Bottle     Home         NaN
311  Bottle     Home       499.0
..      ...      ...         ...
176   Watch  Fashion       999.0
353   Watch  Fashion       999.0
177   Watch  Fashion      4999.0
468   Watch  Fashion      9999.0
167   Watch  Fashion       999.0

[345 rows x 3 columns]

In [226]:
df['unit_price'] = df['unit_price'].fillna(
    df.groupby('category')['unit_price'].transform('median')
)

In [227]:
df.isnull().sum()

order_id          0
order_date        0
customer_name     0
email             0
phone             0
city              0
state             0
product           0
category          0
qty               0
unit_price        0
discount          0
payment_mode      0
order_status      0
delivery_date     0
total_sales      34
net_amount       34
profit           34
order_month       0
order_year        0
order_weekday     0
dtype: int64

In [228]:
df['total_sales'] = df['qty'] * df['unit_price']

In [229]:
df.isnull().sum()

order_id          0
order_date        0
customer_name     0
email             0
phone             0
city              0
state             0
product           0
category          0
qty               0
unit_price        0
discount          0
payment_mode      0
order_status      0
delivery_date     0
total_sales       0
net_amount       34
profit           34
order_month       0
order_year        0
order_weekday     0
dtype: int64

In [230]:
df['net_amount'] = df['total_sales'] * (1 - df['discount'] / 100)
df['profit'] = df['net_amount'] * 0.20

In [231]:
df.isnull().sum()

order_id         0
order_date       0
customer_name    0
email            0
phone            0
city             0
state            0
product          0
category         0
qty              0
unit_price       0
discount         0
payment_mode     0
order_status     0
delivery_date    0
total_sales      0
net_amount       0
profit           0
order_month      0
order_year       0
order_weekday    0
dtype: int64

In [232]:
import sqlite3


conn = sqlite3.connect('sales_database.db')

df.to_sql('orders', conn, if_exists='replace', index=False)

def sql(query):
    return pd.read_sql_query(query, conn)

In [233]:
#Total number ofd orders?
sql("""
SELECT COUNT(*) AS total_orders
FROM orders;
""")

   total_orders
0           345

In [234]:
#Total sales?
sql("""
SELECT SUM(net_amount) AS total_sales
FROM orders;
""")

   total_sales
0    3490602.5

In [235]:
#Top 5 products?
sql("""
SELECT product, SUM(net_amount) AS sales
FROM orders
GROUP BY product
ORDER BY sales DESC
LIMIT 5;
""")

  product      sales
0   Mouse  694328.45
1  Laptop  691961.95
2   Chair  637636.55
3  Bottle  581657.75
4   Watch  477791.60

In [236]:
#Top cities?
sql("""
SELECT city, SUM(net_amount) AS total_sales
FROM orders
GROUP BY city
ORDER BY total_sales DESC
LIMIT 5;
""")

        city  total_sales
0       Pune    801566.45
1  Bengaluru    785855.90
2    Lucknow    525887.45
3      Delhi    520783.30
4     Mumbai    442754.45

In [237]:
#Monthly Sales
sql("""
SELECT order_month, SUM(net_amount) AS total_sales
FROM orders
GROUP BY order_month;
""")

  order_month  total_sales
0       April    653077.35
1    February    661553.55
2     January    433287.05
3        June    724274.05
4       March    289851.80
5         May    728558.70

In [238]:
#Highest Profit Products
sql("""
SELECT product, SUM(profit) AS total_profit
FROM orders
GROUP BY product
ORDER BY total_profit DESC
LIMIT 5;
""")

  product  total_profit
0   Mouse     138865.69
1  Laptop     138392.39
2   Chair     127527.31
3  Bottle     116331.55
4   Watch      95558.32

In [239]:
#payment mode distribution
sql("""
SELECT payment_mode, COUNT(*) AS total_orders
FROM orders
GROUP BY payment_mode
ORDER BY total_orders DESC;
""")

  payment_mode  total_orders
0          COD            81
1   NetBanking            79
2       Wallet            69
3          UPI            63
4         Card            53

In [240]:
#cancelled orders
sql("""
SELECT COUNT(*) AS cancelled_orders
FROM orders
WHERE order_status = 'Cancelled';
""")

   cancelled_orders
0                92